#Default port is 8081
server:
  port: 8081
  
spring:
  cloud:
    stream:
      bindings:
        inboundDogChanges:
          destination: dogOdsTopic
          content-type: application/json
          group: odsGroup
        inboundOwnerChanges:
          destination: ownerOdsTopic
          content-type: application/json
          group: odsGroup
        inboundBreederChanges:
          destination: breederOdsTopic
          content-type: application/json
          group: odsGroup
        inboundTitleChanges:
          destination:  titleOdsTopic
          content-type: application/json
          group: odsGroup
        inboundPedigreeChanges:
          destination:  pedigreeOdsTopic
          content-type: application/json
          group: odsGroup
        inboundParentChanges:
          destination:  parentOdsTopic
          content-type: application/json          
          group: odsGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
  zipkin:
    baseUrl:  http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
        
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.scc: DEBUG      
    org.apache.kafka: WARN  
    org.hibernate: WARN
    